# Site settings
title: goto Interactive Communications
description: >- # this means to ignore newlines until "baseurl:"
  Ботификация жизни начинается здесь. Начато в 2014 году (ГК).
baseurl: ""
url: "https://gotointeractive.com"
github_username: gotois
telegram_username: turbostate

include: ["_pages"]

permalink: /:title/

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
